/// Generated by AssetsRefGenerator on 2020/10/29
class Res {
  static const String 1 = "assets/images/1.jpg";
  static const String 2 = "assets/images/2.png";
  static const String 3 = "assets/images/3.jpg";
  static const String ahmed = "assets/images/ahmed.jpg";
  static const String cu_gate = "assets/images/cu_gate.jpg";
  static const String featurebangla = "assets/images/featurebangla.png";
  static const String friends = "assets/images/friends.jpg";
  static const String images = "assets/images/images.jpg";
  static const String jounalism = "assets/images/jounalism.jpg";
  static const String library = "assets/images/library.jpg";
}
